<?php
use Migrations\AbstractSeed;

/**
 * Cities seed.
 */
class CitiesSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => '114',
                'region_id' => '1',
                'name' => 'Upplands Väsby',
                'description' => NULL,
            ],
            [
                'id' => '115',
                'region_id' => '1',
                'name' => 'Vallentuna',
                'description' => NULL,
            ],
            [
                'id' => '117',
                'region_id' => '1',
                'name' => 'Österåker',
                'description' => NULL,
            ],
            [
                'id' => '120',
                'region_id' => '1',
                'name' => 'Värmdö',
                'description' => NULL,
            ],
            [
                'id' => '123',
                'region_id' => '1',
                'name' => 'Järfälla',
                'description' => NULL,
            ],
            [
                'id' => '125',
                'region_id' => '1',
                'name' => 'Ekerö',
                'description' => NULL,
            ],
            [
                'id' => '126',
                'region_id' => '1',
                'name' => 'Huddinge',
                'description' => NULL,
            ],
            [
                'id' => '127',
                'region_id' => '1',
                'name' => 'Botkyrka',
                'description' => NULL,
            ],
            [
                'id' => '128',
                'region_id' => '1',
                'name' => 'Salem',
                'description' => NULL,
            ],
            [
                'id' => '136',
                'region_id' => '1',
                'name' => 'Haninge',
                'description' => NULL,
            ],
            [
                'id' => '138',
                'region_id' => '1',
                'name' => 'Tyresö',
                'description' => NULL,
            ],
            [
                'id' => '139',
                'region_id' => '1',
                'name' => 'Upplands-Bro',
                'description' => NULL,
            ],
            [
                'id' => '140',
                'region_id' => '1',
                'name' => 'Nykvarn',
                'description' => NULL,
            ],
            [
                'id' => '160',
                'region_id' => '1',
                'name' => 'Täby',
                'description' => NULL,
            ],
            [
                'id' => '162',
                'region_id' => '1',
                'name' => 'Danderyd',
                'description' => NULL,
            ],
            [
                'id' => '163',
                'region_id' => '1',
                'name' => 'Sollentuna',
                'description' => NULL,
            ],
            [
                'id' => '180',
                'region_id' => '1',
                'name' => 'Stockholm',
                'description' => NULL,
            ],
            [
                'id' => '181',
                'region_id' => '1',
                'name' => 'Södertälje',
                'description' => NULL,
            ],
            [
                'id' => '182',
                'region_id' => '1',
                'name' => 'Nacka',
                'description' => NULL,
            ],
            [
                'id' => '183',
                'region_id' => '1',
                'name' => 'Sundbyberg',
                'description' => NULL,
            ],
            [
                'id' => '184',
                'region_id' => '1',
                'name' => 'Solna',
                'description' => NULL,
            ],
            [
                'id' => '186',
                'region_id' => '1',
                'name' => 'Lidingö',
                'description' => NULL,
            ],
            [
                'id' => '187',
                'region_id' => '1',
                'name' => 'Vaxholm',
                'description' => NULL,
            ],
            [
                'id' => '188',
                'region_id' => '1',
                'name' => 'Norrtälje',
                'description' => NULL,
            ],
            [
                'id' => '191',
                'region_id' => '1',
                'name' => 'Sigtuna',
                'description' => NULL,
            ],
            [
                'id' => '192',
                'region_id' => '1',
                'name' => 'Nynäshamn',
                'description' => NULL,
            ],
            [
                'id' => '305',
                'region_id' => '3',
                'name' => 'Håbo',
                'description' => NULL,
            ],
            [
                'id' => '319',
                'region_id' => '3',
                'name' => 'Älvkarleby',
                'description' => NULL,
            ],
            [
                'id' => '330',
                'region_id' => '3',
                'name' => 'Knivsta',
                'description' => NULL,
            ],
            [
                'id' => '331',
                'region_id' => '3',
                'name' => 'Heby',
                'description' => NULL,
            ],
            [
                'id' => '360',
                'region_id' => '3',
                'name' => 'Tierp',
                'description' => NULL,
            ],
            [
                'id' => '380',
                'region_id' => '3',
                'name' => 'Uppsala',
                'description' => NULL,
            ],
            [
                'id' => '381',
                'region_id' => '3',
                'name' => 'Enköping',
                'description' => NULL,
            ],
            [
                'id' => '382',
                'region_id' => '3',
                'name' => 'Östhammar',
                'description' => NULL,
            ],
            [
                'id' => '428',
                'region_id' => '4',
                'name' => 'Vingåker',
                'description' => NULL,
            ],
            [
                'id' => '461',
                'region_id' => '4',
                'name' => 'Gnesta',
                'description' => NULL,
            ],
            [
                'id' => '480',
                'region_id' => '4',
                'name' => 'Nyköping',
                'description' => NULL,
            ],
            [
                'id' => '481',
                'region_id' => '4',
                'name' => 'Oxelösund',
                'description' => NULL,
            ],
            [
                'id' => '482',
                'region_id' => '4',
                'name' => 'Flen',
                'description' => NULL,
            ],
            [
                'id' => '483',
                'region_id' => '4',
                'name' => 'Katrineholm',
                'description' => NULL,
            ],
            [
                'id' => '484',
                'region_id' => '4',
                'name' => 'Eskilstuna',
                'description' => NULL,
            ],
            [
                'id' => '486',
                'region_id' => '4',
                'name' => 'Strängnäs',
                'description' => NULL,
            ],
            [
                'id' => '488',
                'region_id' => '4',
                'name' => 'Trosa',
                'description' => NULL,
            ],
            [
                'id' => '509',
                'region_id' => '5',
                'name' => 'Ödeshög',
                'description' => NULL,
            ],
            [
                'id' => '512',
                'region_id' => '5',
                'name' => 'Ydre',
                'description' => NULL,
            ],
            [
                'id' => '513',
                'region_id' => '5',
                'name' => 'Kinda',
                'description' => NULL,
            ],
            [
                'id' => '560',
                'region_id' => '5',
                'name' => 'Boxholm',
                'description' => NULL,
            ],
            [
                'id' => '561',
                'region_id' => '5',
                'name' => 'Åtvidaberg',
                'description' => NULL,
            ],
            [
                'id' => '562',
                'region_id' => '5',
                'name' => 'Finspång',
                'description' => NULL,
            ],
            [
                'id' => '563',
                'region_id' => '5',
                'name' => 'Valdemarsvik',
                'description' => NULL,
            ],
            [
                'id' => '580',
                'region_id' => '5',
                'name' => 'Linköping',
                'description' => NULL,
            ],
            [
                'id' => '581',
                'region_id' => '5',
                'name' => 'Norrköping',
                'description' => NULL,
            ],
            [
                'id' => '582',
                'region_id' => '5',
                'name' => 'Söderköping',
                'description' => NULL,
            ],
            [
                'id' => '583',
                'region_id' => '5',
                'name' => 'Motala',
                'description' => NULL,
            ],
            [
                'id' => '584',
                'region_id' => '5',
                'name' => 'Vadstena',
                'description' => NULL,
            ],
            [
                'id' => '586',
                'region_id' => '5',
                'name' => 'Mjölby',
                'description' => NULL,
            ],
            [
                'id' => '604',
                'region_id' => '6',
                'name' => 'Aneby',
                'description' => NULL,
            ],
            [
                'id' => '617',
                'region_id' => '6',
                'name' => 'Gnosjö',
                'description' => NULL,
            ],
            [
                'id' => '642',
                'region_id' => '6',
                'name' => 'Mullsjö',
                'description' => NULL,
            ],
            [
                'id' => '643',
                'region_id' => '6',
                'name' => 'Habo',
                'description' => NULL,
            ],
            [
                'id' => '662',
                'region_id' => '6',
                'name' => 'Gislaved',
                'description' => NULL,
            ],
            [
                'id' => '665',
                'region_id' => '6',
                'name' => 'Vaggeryd',
                'description' => NULL,
            ],
            [
                'id' => '680',
                'region_id' => '6',
                'name' => 'Jönköping',
                'description' => NULL,
            ],
            [
                'id' => '682',
                'region_id' => '6',
                'name' => 'Nässjö',
                'description' => NULL,
            ],
            [
                'id' => '683',
                'region_id' => '6',
                'name' => 'Värnamo',
                'description' => NULL,
            ],
            [
                'id' => '684',
                'region_id' => '6',
                'name' => 'Sävsjö',
                'description' => NULL,
            ],
            [
                'id' => '685',
                'region_id' => '6',
                'name' => 'Vetlanda',
                'description' => NULL,
            ],
            [
                'id' => '686',
                'region_id' => '6',
                'name' => 'Eksjö',
                'description' => NULL,
            ],
            [
                'id' => '687',
                'region_id' => '6',
                'name' => 'Tranås',
                'description' => NULL,
            ],
            [
                'id' => '760',
                'region_id' => '7',
                'name' => 'Uppvidinge',
                'description' => NULL,
            ],
            [
                'id' => '761',
                'region_id' => '7',
                'name' => 'Lessebo',
                'description' => NULL,
            ],
            [
                'id' => '763',
                'region_id' => '7',
                'name' => 'Tingsryd',
                'description' => NULL,
            ],
            [
                'id' => '764',
                'region_id' => '7',
                'name' => 'Alvesta',
                'description' => NULL,
            ],
            [
                'id' => '765',
                'region_id' => '7',
                'name' => 'Älmhult',
                'description' => NULL,
            ],
            [
                'id' => '767',
                'region_id' => '7',
                'name' => 'Markaryd',
                'description' => NULL,
            ],
            [
                'id' => '780',
                'region_id' => '7',
                'name' => 'Växjö',
                'description' => NULL,
            ],
            [
                'id' => '781',
                'region_id' => '7',
                'name' => 'Ljungby',
                'description' => NULL,
            ],
            [
                'id' => '821',
                'region_id' => '8',
                'name' => 'Högsby',
                'description' => NULL,
            ],
            [
                'id' => '834',
                'region_id' => '8',
                'name' => 'Torsås',
                'description' => NULL,
            ],
            [
                'id' => '840',
                'region_id' => '8',
                'name' => 'Mörbylånga',
                'description' => NULL,
            ],
            [
                'id' => '860',
                'region_id' => '8',
                'name' => 'Hultsfred',
                'description' => NULL,
            ],
            [
                'id' => '861',
                'region_id' => '8',
                'name' => 'Mönsterås',
                'description' => NULL,
            ],
            [
                'id' => '862',
                'region_id' => '8',
                'name' => 'Emmaboda',
                'description' => NULL,
            ],
            [
                'id' => '880',
                'region_id' => '8',
                'name' => 'Kalmar',
                'description' => NULL,
            ],
            [
                'id' => '881',
                'region_id' => '8',
                'name' => 'Nybro',
                'description' => NULL,
            ],
            [
                'id' => '882',
                'region_id' => '8',
                'name' => 'Oskarshamn',
                'description' => NULL,
            ],
            [
                'id' => '883',
                'region_id' => '8',
                'name' => 'Västervik',
                'description' => NULL,
            ],
            [
                'id' => '884',
                'region_id' => '8',
                'name' => 'Vimmerby',
                'description' => NULL,
            ],
            [
                'id' => '885',
                'region_id' => '8',
                'name' => 'Borgholm',
                'description' => NULL,
            ],
            [
                'id' => '980',
                'region_id' => '9',
                'name' => 'Gotland',
                'description' => NULL,
            ],
            [
                'id' => '1060',
                'region_id' => '10',
                'name' => 'Olofström',
                'description' => NULL,
            ],
            [
                'id' => '1080',
                'region_id' => '10',
                'name' => 'Karlskrona',
                'description' => NULL,
            ],
            [
                'id' => '1081',
                'region_id' => '10',
                'name' => 'Ronneby',
                'description' => NULL,
            ],
            [
                'id' => '1082',
                'region_id' => '10',
                'name' => 'Karlshamn',
                'description' => NULL,
            ],
            [
                'id' => '1083',
                'region_id' => '10',
                'name' => 'Sölvesborg',
                'description' => NULL,
            ],
            [
                'id' => '1214',
                'region_id' => '12',
                'name' => 'Svalöv',
                'description' => NULL,
            ],
            [
                'id' => '1230',
                'region_id' => '12',
                'name' => 'Staffanstorp',
                'description' => NULL,
            ],
            [
                'id' => '1231',
                'region_id' => '12',
                'name' => 'Burlöv',
                'description' => NULL,
            ],
            [
                'id' => '1233',
                'region_id' => '12',
                'name' => 'Vellinge',
                'description' => NULL,
            ],
            [
                'id' => '1256',
                'region_id' => '12',
                'name' => 'Östra Göinge',
                'description' => NULL,
            ],
            [
                'id' => '1257',
                'region_id' => '12',
                'name' => 'Örkelljunga',
                'description' => NULL,
            ],
            [
                'id' => '1260',
                'region_id' => '12',
                'name' => 'Bjuv',
                'description' => NULL,
            ],
            [
                'id' => '1261',
                'region_id' => '12',
                'name' => 'Kävlinge',
                'description' => NULL,
            ],
            [
                'id' => '1262',
                'region_id' => '12',
                'name' => 'Lomma',
                'description' => NULL,
            ],
            [
                'id' => '1263',
                'region_id' => '12',
                'name' => 'Svedala',
                'description' => NULL,
            ],
            [
                'id' => '1264',
                'region_id' => '12',
                'name' => 'Skurup',
                'description' => NULL,
            ],
            [
                'id' => '1265',
                'region_id' => '12',
                'name' => 'Sjöbo',
                'description' => NULL,
            ],
            [
                'id' => '1266',
                'region_id' => '12',
                'name' => 'Hörby',
                'description' => NULL,
            ],
            [
                'id' => '1267',
                'region_id' => '12',
                'name' => 'Höör',
                'description' => NULL,
            ],
            [
                'id' => '1270',
                'region_id' => '12',
                'name' => 'Tomelilla',
                'description' => NULL,
            ],
            [
                'id' => '1272',
                'region_id' => '12',
                'name' => 'Bromölla',
                'description' => NULL,
            ],
            [
                'id' => '1273',
                'region_id' => '12',
                'name' => 'Osby',
                'description' => NULL,
            ],
            [
                'id' => '1275',
                'region_id' => '12',
                'name' => 'Perstorp',
                'description' => NULL,
            ],
            [
                'id' => '1276',
                'region_id' => '12',
                'name' => 'Klippan',
                'description' => NULL,
            ],
            [
                'id' => '1277',
                'region_id' => '12',
                'name' => 'Åstorp',
                'description' => NULL,
            ],
            [
                'id' => '1278',
                'region_id' => '12',
                'name' => 'Båstad',
                'description' => NULL,
            ],
            [
                'id' => '1280',
                'region_id' => '12',
                'name' => 'Malmö',
                'description' => NULL,
            ],
            [
                'id' => '1281',
                'region_id' => '12',
                'name' => 'Lund',
                'description' => NULL,
            ],
            [
                'id' => '1282',
                'region_id' => '12',
                'name' => 'Landskrona',
                'description' => NULL,
            ],
            [
                'id' => '1283',
                'region_id' => '12',
                'name' => 'Helsingborg',
                'description' => NULL,
            ],
            [
                'id' => '1284',
                'region_id' => '12',
                'name' => 'Höganäs',
                'description' => NULL,
            ],
            [
                'id' => '1285',
                'region_id' => '12',
                'name' => 'Eslöv',
                'description' => NULL,
            ],
            [
                'id' => '1286',
                'region_id' => '12',
                'name' => 'Ystad',
                'description' => NULL,
            ],
            [
                'id' => '1287',
                'region_id' => '12',
                'name' => 'Trelleborg',
                'description' => NULL,
            ],
            [
                'id' => '1290',
                'region_id' => '12',
                'name' => 'Kristianstad',
                'description' => NULL,
            ],
            [
                'id' => '1291',
                'region_id' => '12',
                'name' => 'Simrishamn',
                'description' => NULL,
            ],
            [
                'id' => '1292',
                'region_id' => '12',
                'name' => 'Ängelholm',
                'description' => NULL,
            ],
            [
                'id' => '1293',
                'region_id' => '12',
                'name' => 'Hässleholm',
                'description' => NULL,
            ],
            [
                'id' => '1315',
                'region_id' => '13',
                'name' => 'Hylte',
                'description' => NULL,
            ],
            [
                'id' => '1380',
                'region_id' => '13',
                'name' => 'Halmstad',
                'description' => NULL,
            ],
            [
                'id' => '1381',
                'region_id' => '13',
                'name' => 'Laholm',
                'description' => NULL,
            ],
            [
                'id' => '1382',
                'region_id' => '13',
                'name' => 'Falkenberg',
                'description' => NULL,
            ],
            [
                'id' => '1383',
                'region_id' => '13',
                'name' => 'Varberg',
                'description' => NULL,
            ],
            [
                'id' => '1384',
                'region_id' => '13',
                'name' => 'Kungsbacka',
                'description' => NULL,
            ],
            [
                'id' => '1401',
                'region_id' => '14',
                'name' => 'Härryda',
                'description' => NULL,
            ],
            [
                'id' => '1402',
                'region_id' => '14',
                'name' => 'Partille',
                'description' => NULL,
            ],
            [
                'id' => '1407',
                'region_id' => '14',
                'name' => 'Öckerö',
                'description' => NULL,
            ],
            [
                'id' => '1415',
                'region_id' => '14',
                'name' => 'Stenungsund',
                'description' => NULL,
            ],
            [
                'id' => '1419',
                'region_id' => '14',
                'name' => 'Tjörn',
                'description' => NULL,
            ],
            [
                'id' => '1421',
                'region_id' => '14',
                'name' => 'Orust',
                'description' => NULL,
            ],
            [
                'id' => '1427',
                'region_id' => '14',
                'name' => 'Sotenäs',
                'description' => NULL,
            ],
            [
                'id' => '1430',
                'region_id' => '14',
                'name' => 'Munkedal',
                'description' => NULL,
            ],
            [
                'id' => '1435',
                'region_id' => '14',
                'name' => 'Tanum',
                'description' => NULL,
            ],
            [
                'id' => '1438',
                'region_id' => '14',
                'name' => 'Dals-Ed',
                'description' => NULL,
            ],
            [
                'id' => '1439',
                'region_id' => '14',
                'name' => 'Färgelanda',
                'description' => NULL,
            ],
            [
                'id' => '1440',
                'region_id' => '14',
                'name' => 'Ale',
                'description' => NULL,
            ],
            [
                'id' => '1441',
                'region_id' => '14',
                'name' => 'Lerum',
                'description' => NULL,
            ],
            [
                'id' => '1442',
                'region_id' => '14',
                'name' => 'Vårgårda',
                'description' => NULL,
            ],
            [
                'id' => '1443',
                'region_id' => '14',
                'name' => 'Bollebygd',
                'description' => NULL,
            ],
            [
                'id' => '1444',
                'region_id' => '14',
                'name' => 'Grästorp',
                'description' => NULL,
            ],
            [
                'id' => '1445',
                'region_id' => '14',
                'name' => 'Essunga',
                'description' => NULL,
            ],
            [
                'id' => '1446',
                'region_id' => '14',
                'name' => 'Karlsborg',
                'description' => NULL,
            ],
            [
                'id' => '1447',
                'region_id' => '14',
                'name' => 'Gullspång',
                'description' => NULL,
            ],
            [
                'id' => '1452',
                'region_id' => '14',
                'name' => 'Tranemo',
                'description' => NULL,
            ],
            [
                'id' => '1460',
                'region_id' => '14',
                'name' => 'Bengtsfors',
                'description' => NULL,
            ],
            [
                'id' => '1461',
                'region_id' => '14',
                'name' => 'Mellerud',
                'description' => NULL,
            ],
            [
                'id' => '1462',
                'region_id' => '14',
                'name' => 'Lilla Edet',
                'description' => NULL,
            ],
            [
                'id' => '1463',
                'region_id' => '14',
                'name' => 'Mark',
                'description' => NULL,
            ],
            [
                'id' => '1465',
                'region_id' => '14',
                'name' => 'Svenljunga',
                'description' => NULL,
            ],
            [
                'id' => '1466',
                'region_id' => '14',
                'name' => 'Herrljunga',
                'description' => NULL,
            ],
            [
                'id' => '1470',
                'region_id' => '14',
                'name' => 'Vara',
                'description' => NULL,
            ],
            [
                'id' => '1471',
                'region_id' => '14',
                'name' => 'Götene',
                'description' => NULL,
            ],
            [
                'id' => '1472',
                'region_id' => '14',
                'name' => 'Tibro',
                'description' => NULL,
            ],
            [
                'id' => '1473',
                'region_id' => '14',
                'name' => 'Töreboda',
                'description' => NULL,
            ],
            [
                'id' => '1480',
                'region_id' => '14',
                'name' => 'Göteborg',
                'description' => NULL,
            ],
            [
                'id' => '1481',
                'region_id' => '14',
                'name' => 'Mölndal',
                'description' => NULL,
            ],
            [
                'id' => '1482',
                'region_id' => '14',
                'name' => 'Kungälv',
                'description' => NULL,
            ],
            [
                'id' => '1484',
                'region_id' => '14',
                'name' => 'Lysekil',
                'description' => NULL,
            ],
            [
                'id' => '1485',
                'region_id' => '14',
                'name' => 'Uddevalla',
                'description' => NULL,
            ],
            [
                'id' => '1486',
                'region_id' => '14',
                'name' => 'Strömstad',
                'description' => NULL,
            ],
            [
                'id' => '1487',
                'region_id' => '14',
                'name' => 'Vänersborg',
                'description' => NULL,
            ],
            [
                'id' => '1488',
                'region_id' => '14',
                'name' => 'Trollhättan',
                'description' => NULL,
            ],
            [
                'id' => '1489',
                'region_id' => '14',
                'name' => 'Alingsås',
                'description' => NULL,
            ],
            [
                'id' => '1490',
                'region_id' => '14',
                'name' => 'Borås',
                'description' => NULL,
            ],
            [
                'id' => '1491',
                'region_id' => '14',
                'name' => 'Ulricehamn',
                'description' => NULL,
            ],
            [
                'id' => '1492',
                'region_id' => '14',
                'name' => 'Åmål',
                'description' => NULL,
            ],
            [
                'id' => '1493',
                'region_id' => '14',
                'name' => 'Mariestad',
                'description' => NULL,
            ],
            [
                'id' => '1494',
                'region_id' => '14',
                'name' => 'Lidköping',
                'description' => NULL,
            ],
            [
                'id' => '1495',
                'region_id' => '14',
                'name' => 'Skara',
                'description' => NULL,
            ],
            [
                'id' => '1496',
                'region_id' => '14',
                'name' => 'Skövde',
                'description' => NULL,
            ],
            [
                'id' => '1497',
                'region_id' => '14',
                'name' => 'Hjo',
                'description' => NULL,
            ],
            [
                'id' => '1498',
                'region_id' => '14',
                'name' => 'Tidaholm',
                'description' => NULL,
            ],
            [
                'id' => '1499',
                'region_id' => '14',
                'name' => 'Falköping',
                'description' => NULL,
            ],
            [
                'id' => '1715',
                'region_id' => '17',
                'name' => 'Kil',
                'description' => NULL,
            ],
            [
                'id' => '1730',
                'region_id' => '17',
                'name' => 'Eda',
                'description' => NULL,
            ],
            [
                'id' => '1737',
                'region_id' => '17',
                'name' => 'Torsby',
                'description' => NULL,
            ],
            [
                'id' => '1760',
                'region_id' => '17',
                'name' => 'Storfors',
                'description' => NULL,
            ],
            [
                'id' => '1761',
                'region_id' => '17',
                'name' => 'Hammarö',
                'description' => NULL,
            ],
            [
                'id' => '1762',
                'region_id' => '17',
                'name' => 'Munkfors',
                'description' => NULL,
            ],
            [
                'id' => '1763',
                'region_id' => '17',
                'name' => 'Forshaga',
                'description' => NULL,
            ],
            [
                'id' => '1764',
                'region_id' => '17',
                'name' => 'Grums',
                'description' => NULL,
            ],
            [
                'id' => '1765',
                'region_id' => '17',
                'name' => 'Årjäng',
                'description' => NULL,
            ],
            [
                'id' => '1766',
                'region_id' => '17',
                'name' => 'Sunne',
                'description' => NULL,
            ],
            [
                'id' => '1780',
                'region_id' => '17',
                'name' => 'Karlstad',
                'description' => NULL,
            ],
            [
                'id' => '1781',
                'region_id' => '17',
                'name' => 'Kristinehamn',
                'description' => NULL,
            ],
            [
                'id' => '1782',
                'region_id' => '17',
                'name' => 'Filipstad',
                'description' => NULL,
            ],
            [
                'id' => '1783',
                'region_id' => '17',
                'name' => 'Hagfors',
                'description' => NULL,
            ],
            [
                'id' => '1784',
                'region_id' => '17',
                'name' => 'Arvika',
                'description' => NULL,
            ],
            [
                'id' => '1785',
                'region_id' => '17',
                'name' => 'Säffle',
                'description' => NULL,
            ],
            [
                'id' => '1814',
                'region_id' => '18',
                'name' => 'Lekeberg',
                'description' => NULL,
            ],
            [
                'id' => '1860',
                'region_id' => '18',
                'name' => 'Laxå',
                'description' => NULL,
            ],
            [
                'id' => '1861',
                'region_id' => '18',
                'name' => 'Hallsberg',
                'description' => NULL,
            ],
            [
                'id' => '1862',
                'region_id' => '18',
                'name' => 'Degerfors',
                'description' => NULL,
            ],
            [
                'id' => '1863',
                'region_id' => '18',
                'name' => 'Hällefors',
                'description' => NULL,
            ],
            [
                'id' => '1864',
                'region_id' => '18',
                'name' => 'Ljusnarsberg',
                'description' => NULL,
            ],
            [
                'id' => '1880',
                'region_id' => '18',
                'name' => 'Örebro',
                'description' => NULL,
            ],
            [
                'id' => '1881',
                'region_id' => '18',
                'name' => 'Kumla',
                'description' => NULL,
            ],
            [
                'id' => '1882',
                'region_id' => '18',
                'name' => 'Askersund',
                'description' => NULL,
            ],
            [
                'id' => '1883',
                'region_id' => '18',
                'name' => 'Karlskoga',
                'description' => NULL,
            ],
            [
                'id' => '1884',
                'region_id' => '18',
                'name' => 'Nora',
                'description' => NULL,
            ],
            [
                'id' => '1885',
                'region_id' => '18',
                'name' => 'Lindesberg',
                'description' => NULL,
            ],
            [
                'id' => '1904',
                'region_id' => '19',
                'name' => 'Skinnskatteberg',
                'description' => NULL,
            ],
            [
                'id' => '1907',
                'region_id' => '19',
                'name' => 'Surahammar',
                'description' => NULL,
            ],
            [
                'id' => '1960',
                'region_id' => '19',
                'name' => 'Kungsör',
                'description' => NULL,
            ],
            [
                'id' => '1961',
                'region_id' => '19',
                'name' => 'Hallstahammar',
                'description' => NULL,
            ],
            [
                'id' => '1962',
                'region_id' => '19',
                'name' => 'Norberg',
                'description' => NULL,
            ],
            [
                'id' => '1980',
                'region_id' => '19',
                'name' => 'Västerås',
                'description' => NULL,
            ],
            [
                'id' => '1981',
                'region_id' => '19',
                'name' => 'Sala',
                'description' => NULL,
            ],
            [
                'id' => '1982',
                'region_id' => '19',
                'name' => 'Fagersta',
                'description' => NULL,
            ],
            [
                'id' => '1983',
                'region_id' => '19',
                'name' => 'Köping',
                'description' => NULL,
            ],
            [
                'id' => '1984',
                'region_id' => '19',
                'name' => 'Arboga',
                'description' => NULL,
            ],
            [
                'id' => '2021',
                'region_id' => '20',
                'name' => 'Vansbro',
                'description' => NULL,
            ],
            [
                'id' => '2023',
                'region_id' => '20',
                'name' => 'Malung-Sälen',
                'description' => NULL,
            ],
            [
                'id' => '2026',
                'region_id' => '20',
                'name' => 'Gagnef',
                'description' => NULL,
            ],
            [
                'id' => '2029',
                'region_id' => '20',
                'name' => 'Leksand',
                'description' => NULL,
            ],
            [
                'id' => '2031',
                'region_id' => '20',
                'name' => 'Rättvik',
                'description' => NULL,
            ],
            [
                'id' => '2034',
                'region_id' => '20',
                'name' => 'Orsa',
                'description' => NULL,
            ],
            [
                'id' => '2039',
                'region_id' => '20',
                'name' => 'Älvdalen',
                'description' => NULL,
            ],
            [
                'id' => '2061',
                'region_id' => '20',
                'name' => 'Smedjebacken',
                'description' => NULL,
            ],
            [
                'id' => '2062',
                'region_id' => '20',
                'name' => 'Mora',
                'description' => NULL,
            ],
            [
                'id' => '2080',
                'region_id' => '20',
                'name' => 'Falun',
                'description' => NULL,
            ],
            [
                'id' => '2081',
                'region_id' => '20',
                'name' => 'Borlänge',
                'description' => NULL,
            ],
            [
                'id' => '2082',
                'region_id' => '20',
                'name' => 'Säter',
                'description' => NULL,
            ],
            [
                'id' => '2083',
                'region_id' => '20',
                'name' => 'Hedemora',
                'description' => NULL,
            ],
            [
                'id' => '2084',
                'region_id' => '20',
                'name' => 'Avesta',
                'description' => NULL,
            ],
            [
                'id' => '2085',
                'region_id' => '20',
                'name' => 'Ludvika',
                'description' => NULL,
            ],
            [
                'id' => '2101',
                'region_id' => '21',
                'name' => 'Ockelbo',
                'description' => NULL,
            ],
            [
                'id' => '2104',
                'region_id' => '21',
                'name' => 'Hofors',
                'description' => NULL,
            ],
            [
                'id' => '2121',
                'region_id' => '21',
                'name' => 'Ovanåker',
                'description' => NULL,
            ],
            [
                'id' => '2132',
                'region_id' => '21',
                'name' => 'Nordanstig',
                'description' => NULL,
            ],
            [
                'id' => '2161',
                'region_id' => '21',
                'name' => 'Ljusdal',
                'description' => NULL,
            ],
            [
                'id' => '2180',
                'region_id' => '21',
                'name' => 'Gävle',
                'description' => NULL,
            ],
            [
                'id' => '2181',
                'region_id' => '21',
                'name' => 'Sandviken',
                'description' => NULL,
            ],
            [
                'id' => '2182',
                'region_id' => '21',
                'name' => 'Söderhamn',
                'description' => NULL,
            ],
            [
                'id' => '2183',
                'region_id' => '21',
                'name' => 'Bollnäs',
                'description' => NULL,
            ],
            [
                'id' => '2184',
                'region_id' => '21',
                'name' => 'Hudiksvall',
                'description' => NULL,
            ],
            [
                'id' => '2260',
                'region_id' => '22',
                'name' => 'Ånge',
                'description' => NULL,
            ],
            [
                'id' => '2262',
                'region_id' => '22',
                'name' => 'Timrå',
                'description' => NULL,
            ],
            [
                'id' => '2280',
                'region_id' => '22',
                'name' => 'Härnösand',
                'description' => NULL,
            ],
            [
                'id' => '2281',
                'region_id' => '22',
                'name' => 'Sundsvall',
                'description' => NULL,
            ],
            [
                'id' => '2282',
                'region_id' => '22',
                'name' => 'Kramfors',
                'description' => NULL,
            ],
            [
                'id' => '2283',
                'region_id' => '22',
                'name' => 'Sollefteå',
                'description' => NULL,
            ],
            [
                'id' => '2284',
                'region_id' => '22',
                'name' => 'Örnsköldsvik',
                'description' => NULL,
            ],
            [
                'id' => '2303',
                'region_id' => '23',
                'name' => 'Ragunda',
                'description' => NULL,
            ],
            [
                'id' => '2305',
                'region_id' => '23',
                'name' => 'Bräcke',
                'description' => NULL,
            ],
            [
                'id' => '2309',
                'region_id' => '23',
                'name' => 'Krokom',
                'description' => NULL,
            ],
            [
                'id' => '2313',
                'region_id' => '23',
                'name' => 'Strömsund',
                'description' => NULL,
            ],
            [
                'id' => '2321',
                'region_id' => '23',
                'name' => 'Åre',
                'description' => NULL,
            ],
            [
                'id' => '2326',
                'region_id' => '23',
                'name' => 'Berg',
                'description' => NULL,
            ],
            [
                'id' => '2361',
                'region_id' => '23',
                'name' => 'Härjedalen',
                'description' => NULL,
            ],
            [
                'id' => '2380',
                'region_id' => '23',
                'name' => 'Östersund',
                'description' => NULL,
            ],
            [
                'id' => '2401',
                'region_id' => '24',
                'name' => 'Nordmaling',
                'description' => NULL,
            ],
            [
                'id' => '2403',
                'region_id' => '24',
                'name' => 'Bjurholm',
                'description' => NULL,
            ],
            [
                'id' => '2404',
                'region_id' => '24',
                'name' => 'Vindeln',
                'description' => NULL,
            ],
            [
                'id' => '2409',
                'region_id' => '24',
                'name' => 'Robertsfors',
                'description' => NULL,
            ],
            [
                'id' => '2417',
                'region_id' => '24',
                'name' => 'Norsjö',
                'description' => NULL,
            ],
            [
                'id' => '2418',
                'region_id' => '24',
                'name' => 'Malå',
                'description' => NULL,
            ],
            [
                'id' => '2421',
                'region_id' => '24',
                'name' => 'Storuman',
                'description' => NULL,
            ],
            [
                'id' => '2422',
                'region_id' => '24',
                'name' => 'Sorsele',
                'description' => NULL,
            ],
            [
                'id' => '2425',
                'region_id' => '24',
                'name' => 'Dorotea',
                'description' => NULL,
            ],
            [
                'id' => '2460',
                'region_id' => '24',
                'name' => 'Vännäs',
                'description' => NULL,
            ],
            [
                'id' => '2462',
                'region_id' => '24',
                'name' => 'Vilhelmina',
                'description' => NULL,
            ],
            [
                'id' => '2463',
                'region_id' => '24',
                'name' => 'Åsele',
                'description' => NULL,
            ],
            [
                'id' => '2480',
                'region_id' => '24',
                'name' => 'Umeå',
                'description' => NULL,
            ],
            [
                'id' => '2481',
                'region_id' => '24',
                'name' => 'Lycksele',
                'description' => NULL,
            ],
            [
                'id' => '2482',
                'region_id' => '24',
                'name' => 'Skellefteå',
                'description' => NULL,
            ],
            [
                'id' => '2505',
                'region_id' => '25',
                'name' => 'Arvidsjaur',
                'description' => NULL,
            ],
            [
                'id' => '2506',
                'region_id' => '25',
                'name' => 'Arjeplog',
                'description' => NULL,
            ],
            [
                'id' => '2510',
                'region_id' => '25',
                'name' => 'Jokkmokk',
                'description' => NULL,
            ],
            [
                'id' => '2513',
                'region_id' => '25',
                'name' => 'Överkalix',
                'description' => NULL,
            ],
            [
                'id' => '2514',
                'region_id' => '25',
                'name' => 'Kalix',
                'description' => NULL,
            ],
            [
                'id' => '2518',
                'region_id' => '25',
                'name' => 'Övertorneå',
                'description' => NULL,
            ],
            [
                'id' => '2521',
                'region_id' => '25',
                'name' => 'Pajala',
                'description' => NULL,
            ],
            [
                'id' => '2523',
                'region_id' => '25',
                'name' => 'Gällivare',
                'description' => NULL,
            ],
            [
                'id' => '2560',
                'region_id' => '25',
                'name' => 'Älvsbyn',
                'description' => NULL,
            ],
            [
                'id' => '2580',
                'region_id' => '25',
                'name' => 'Luleå',
                'description' => NULL,
            ],
            [
                'id' => '2581',
                'region_id' => '25',
                'name' => 'Piteå',
                'description' => NULL,
            ],
            [
                'id' => '2582',
                'region_id' => '25',
                'name' => 'Boden',
                'description' => NULL,
            ],
            [
                'id' => '2583',
                'region_id' => '25',
                'name' => 'Haparanda',
                'description' => NULL,
            ],
            [
                'id' => '2584',
                'region_id' => '25',
                'name' => 'Kiruna',
                'description' => NULL,
            ],
        ];

        $table = $this->table('cities');
        $table->insert($data)->save();
    }
}
